apiVersion: v1
kind: Service
metadata:
  name: {{ template "tradfik.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: port80
    - port: 8080
      targetPort: 8080
      name: port8080
  selector:
    app: {{ template "tradfik.name" . }}

