apiVersion: v1
kind: Service
metadata:
  name: {{ template "httpd.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      nodePort: 
  selector:
    app: {{ template "httpd.name" . }}
    release: "{{ .Release.Name }}"

