apiVersion: v1
kind: Service
metadata:
  name: {{ template "wordpress.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ template "wordpress.name" . }}
    release: "{{ .Release.Name }}"

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "wordpress.fullname" . }}-database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: {{ template "wordpress.name" . }}-database
    release: "{{ .Release.Name }}"-database
