apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "piwik.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "piwik.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "piwik.name" . }}
    spec:
      containers:
        - name: piwik
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}         
          ports:
          - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "piwik.fullname" . }}-database
spec:
  selector:
    matchLabels:
      app: {{ template "piwik.name" . }}-database
  template:
    metadata:
      labels:
        app: {{ template "piwik.name" . }}-database
    spec:
      containers:
        - name: piwik-database
          image: "{{ .Values.dbimage.repository }}:{{ .Values.dbimage.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
          - name: MYSQL_USER
            value: piwik
          - name: MYSQL_PASSWORD
            value: piwik           
          - name: MYSQL_DATABASE
            value: piwik
          - name: MYSQL_ROOT_PASSWORD
            value: piwik
          ports:
          - containerPort: 3306
